# Generated by Django 2.1.5 on 2019-02-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('WHOLESALER', 'WHOLESALER'), ('CUSTOMER', 'CUSTOMER'), ('DELIVERY_MAN', 'DELIVERY_MAN')], max_length=50),
        ),
    ]
