# Generated by Django 2.1.5 on 2019-02-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190209_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesalerproduct',
            name='image',
        ),
        migrations.RemoveField(
            model_name='wholesalerproduct',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('g', 'g'), ('No(s)', 'No(s)'), ('l', 'l')], default='Kg', max_length=20),
            preserve_default=False,
        ),
    ]
