# Generated by Django 2.1.5 on 2019-05-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20190526_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_edited',
            field=models.BooleanField(default=True),
        ),
    ]
