# Generated by Django 2.1.5 on 2019-06-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20190526_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='fav_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
