# Generated by Django 2.1.5 on 2019-07-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20190702_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderedproducts',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
