# Generated by Django 2.1.5 on 2019-07-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_order_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
