# Generated by Django 2.1.5 on 2019-07-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20190707_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproducts',
            name='is_admin_buyed',
            field=models.BooleanField(default=False),
        ),
    ]
